// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CreateScheduleRequestEnvironment.
const (
	CreateScheduleRequestEnvironmentDevelopment CreateScheduleRequestEnvironment = "development"
	CreateScheduleRequestEnvironmentProduction  CreateScheduleRequestEnvironment = "production"
	CreateScheduleRequestEnvironmentStaging     CreateScheduleRequestEnvironment = "staging"
)

// Valid indicates whether the value is a known member of the CreateScheduleRequestEnvironment enum.
func (e CreateScheduleRequestEnvironment) Valid() bool {
	switch e {
	case CreateScheduleRequestEnvironmentDevelopment:
		return true
	case CreateScheduleRequestEnvironmentProduction:
		return true
	case CreateScheduleRequestEnvironmentStaging:
		return true
	default:
		return false
	}
}

// Defines values for ScheduleEnvironment.
const (
	ScheduleEnvironmentDevelopment ScheduleEnvironment = "development"
	ScheduleEnvironmentProduction  ScheduleEnvironment = "production"
	ScheduleEnvironmentStaging     ScheduleEnvironment = "staging"
)

// Valid indicates whether the value is a known member of the ScheduleEnvironment enum.
func (e ScheduleEnvironment) Valid() bool {
	switch e {
	case ScheduleEnvironmentDevelopment:
		return true
	case ScheduleEnvironmentProduction:
		return true
	case ScheduleEnvironmentStaging:
		return true
	default:
		return false
	}
}

// Defines values for ScheduleStatus.
const (
	ScheduleStatusApproved ScheduleStatus = "approved"
	ScheduleStatusCreated  ScheduleStatus = "created"
	ScheduleStatusDenied   ScheduleStatus = "denied"
)

// Valid indicates whether the value is a known member of the ScheduleStatus enum.
func (e ScheduleStatus) Valid() bool {
	switch e {
	case ScheduleStatusApproved:
		return true
	case ScheduleStatusCreated:
		return true
	case ScheduleStatusDenied:
		return true
	default:
		return false
	}
}

// Defines values for UpdateScheduleRequestEnvironment.
const (
	UpdateScheduleRequestEnvironmentDevelopment UpdateScheduleRequestEnvironment = "development"
	UpdateScheduleRequestEnvironmentProduction  UpdateScheduleRequestEnvironment = "production"
	UpdateScheduleRequestEnvironmentStaging     UpdateScheduleRequestEnvironment = "staging"
)

// Valid indicates whether the value is a known member of the UpdateScheduleRequestEnvironment enum.
func (e UpdateScheduleRequestEnvironment) Valid() bool {
	switch e {
	case UpdateScheduleRequestEnvironmentDevelopment:
		return true
	case UpdateScheduleRequestEnvironmentProduction:
		return true
	case UpdateScheduleRequestEnvironmentStaging:
		return true
	default:
		return false
	}
}

// Defines values for ListSchedulesParamsEnvironment.
const (
	ListSchedulesParamsEnvironmentDevelopment ListSchedulesParamsEnvironment = "development"
	ListSchedulesParamsEnvironmentProduction  ListSchedulesParamsEnvironment = "production"
	ListSchedulesParamsEnvironmentStaging     ListSchedulesParamsEnvironment = "staging"
)

// Valid indicates whether the value is a known member of the ListSchedulesParamsEnvironment enum.
func (e ListSchedulesParamsEnvironment) Valid() bool {
	switch e {
	case ListSchedulesParamsEnvironmentDevelopment:
		return true
	case ListSchedulesParamsEnvironmentProduction:
		return true
	case ListSchedulesParamsEnvironmentStaging:
		return true
	default:
		return false
	}
}

// Defines values for ListSchedulesParamsStatus.
const (
	ListSchedulesParamsStatusApproved ListSchedulesParamsStatus = "approved"
	ListSchedulesParamsStatusCreated  ListSchedulesParamsStatus = "created"
	ListSchedulesParamsStatusDenied   ListSchedulesParamsStatus = "denied"
)

// Valid indicates whether the value is a known member of the ListSchedulesParamsStatus enum.
func (e ListSchedulesParamsStatus) Valid() bool {
	switch e {
	case ListSchedulesParamsStatusApproved:
		return true
	case ListSchedulesParamsStatusCreated:
		return true
	case ListSchedulesParamsStatusDenied:
		return true
	default:
		return false
	}
}

// CreateScheduleRequest defines model for CreateScheduleRequest.
type CreateScheduleRequest struct {
	// Description Optional description of the deployment
	Description *string `json:"description,omitempty"`

	// Environment Target environment
	Environment CreateScheduleRequestEnvironment `json:"environment"`

	// Owner Owner of the schedule
	Owner string `json:"owner"`

	// RollbackPlan Optional rollback plan for the deployment
	RollbackPlan *string `json:"rollbackPlan,omitempty"`

	// ScheduledAt When the deployment is scheduled (ISO 8601)
	ScheduledAt time.Time `json:"scheduledAt"`

	// ServiceName Name of the service to deploy
	ServiceName string `json:"serviceName"`
}

// CreateScheduleRequestEnvironment Target environment
type CreateScheduleRequestEnvironment string

// Error defines model for Error.
type Error struct {
	// Details Additional error details
	Details *string `json:"details,omitempty"`

	// Message Error message
	Message string `json:"message"`
}

// Schedule defines model for Schedule.
type Schedule struct {
	// CreatedAt When the schedule was created
	CreatedAt time.Time `json:"createdAt"`

	// Description Optional description of the deployment
	Description *string `json:"description,omitempty"`

	// Environment Target environment
	Environment ScheduleEnvironment `json:"environment"`

	// Id Unique schedule identifier
	Id openapi_types.UUID `json:"id"`

	// Owner Owner of the schedule (immutable after creation)
	Owner string `json:"owner"`

	// RollbackPlan Optional rollback plan for the deployment
	RollbackPlan *string `json:"rollbackPlan,omitempty"`

	// ScheduledAt When the deployment is scheduled (ISO 8601)
	ScheduledAt time.Time `json:"scheduledAt"`

	// ServiceName Name of the service to deploy
	ServiceName string `json:"serviceName"`

	// Status Approval status of the schedule
	Status ScheduleStatus `json:"status"`

	// UpdatedAt When the schedule was last updated
	UpdatedAt time.Time `json:"updatedAt"`
}

// ScheduleEnvironment Target environment
type ScheduleEnvironment string

// ScheduleStatus Approval status of the schedule
type ScheduleStatus string

// UpdateScheduleRequest defines model for UpdateScheduleRequest.
type UpdateScheduleRequest struct {
	// Description Optional description of the deployment
	Description *string `json:"description,omitempty"`

	// Environment Target environment
	Environment *UpdateScheduleRequestEnvironment `json:"environment,omitempty"`

	// RollbackPlan Optional rollback plan for the deployment
	RollbackPlan *string `json:"rollbackPlan,omitempty"`

	// ScheduledAt When the deployment is scheduled (ISO 8601)
	ScheduledAt *time.Time `json:"scheduledAt,omitempty"`

	// ServiceName Name of the service to deploy
	ServiceName *string `json:"serviceName,omitempty"`
}

// UpdateScheduleRequestEnvironment Target environment
type UpdateScheduleRequestEnvironment string

// ListSchedulesParams defines parameters for ListSchedules.
type ListSchedulesParams struct {
	// From Start date for filtering (ISO 8601 format)
	From *time.Time `form:"from,omitempty" json:"from,omitempty"`

	// To End date for filtering (ISO 8601 format)
	To *time.Time `form:"to,omitempty" json:"to,omitempty"`

	// Environment Filter by environment
	Environment *ListSchedulesParamsEnvironment `form:"environment,omitempty" json:"environment,omitempty"`

	// Owner Filter by owner
	Owner *string `form:"owner,omitempty" json:"owner,omitempty"`

	// Status Filter by status
	Status *ListSchedulesParamsStatus `form:"status,omitempty" json:"status,omitempty"`
}

// ListSchedulesParamsEnvironment defines parameters for ListSchedules.
type ListSchedulesParamsEnvironment string

// ListSchedulesParamsStatus defines parameters for ListSchedules.
type ListSchedulesParamsStatus string

// CreateScheduleJSONRequestBody defines body for CreateSchedule for application/json ContentType.
type CreateScheduleJSONRequestBody = CreateScheduleRequest

// UpdateScheduleJSONRequestBody defines body for UpdateSchedule for application/json ContentType.
type UpdateScheduleJSONRequestBody = UpdateScheduleRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List deployment schedules
	// (GET /schedules)
	ListSchedules(w http.ResponseWriter, r *http.Request, params ListSchedulesParams)
	// Create a new deployment schedule
	// (POST /schedules)
	CreateSchedule(w http.ResponseWriter, r *http.Request)
	// Delete a schedule
	// (DELETE /schedules/{id})
	DeleteSchedule(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Get a schedule by ID
	// (GET /schedules/{id})
	GetSchedule(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Update a schedule
	// (PUT /schedules/{id})
	UpdateSchedule(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Approve a schedule
	// (POST /schedules/{id}/approve)
	ApproveSchedule(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Deny a schedule
	// (POST /schedules/{id}/deny)
	DenySchedule(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List deployment schedules
// (GET /schedules)
func (_ Unimplemented) ListSchedules(w http.ResponseWriter, r *http.Request, params ListSchedulesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new deployment schedule
// (POST /schedules)
func (_ Unimplemented) CreateSchedule(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a schedule
// (DELETE /schedules/{id})
func (_ Unimplemented) DeleteSchedule(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a schedule by ID
// (GET /schedules/{id})
func (_ Unimplemented) GetSchedule(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a schedule
// (PUT /schedules/{id})
func (_ Unimplemented) UpdateSchedule(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Approve a schedule
// (POST /schedules/{id}/approve)
func (_ Unimplemented) ApproveSchedule(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Deny a schedule
// (POST /schedules/{id}/deny)
func (_ Unimplemented) DenySchedule(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListSchedules operation middleware
func (siw *ServerInterfaceWrapper) ListSchedules(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListSchedulesParams

	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "from", r.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		return
	}

	// ------------- Optional query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "to", r.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		return
	}

	// ------------- Optional query parameter "environment" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "environment", r.URL.Query(), &params.Environment, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "environment", Err: err})
		return
	}

	// ------------- Optional query parameter "owner" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "owner", r.URL.Query(), &params.Owner, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "owner", Err: err})
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSchedules(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateSchedule operation middleware
func (siw *ServerInterfaceWrapper) CreateSchedule(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateSchedule(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteSchedule operation middleware
func (siw *ServerInterfaceWrapper) DeleteSchedule(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteSchedule(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSchedule operation middleware
func (siw *ServerInterfaceWrapper) GetSchedule(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSchedule(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateSchedule operation middleware
func (siw *ServerInterfaceWrapper) UpdateSchedule(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateSchedule(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ApproveSchedule operation middleware
func (siw *ServerInterfaceWrapper) ApproveSchedule(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ApproveSchedule(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DenySchedule operation middleware
func (siw *ServerInterfaceWrapper) DenySchedule(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DenySchedule(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/schedules", wrapper.ListSchedules)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/schedules", wrapper.CreateSchedule)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/schedules/{id}", wrapper.DeleteSchedule)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/schedules/{id}", wrapper.GetSchedule)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/schedules/{id}", wrapper.UpdateSchedule)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/schedules/{id}/approve", wrapper.ApproveSchedule)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/schedules/{id}/deny", wrapper.DenySchedule)
	})

	return r
}
