// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"context"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for CreateScheduleRequestEnvironments.
const (
	CreateScheduleRequestEnvironmentsDevelopment CreateScheduleRequestEnvironments = "development"
	CreateScheduleRequestEnvironmentsProduction  CreateScheduleRequestEnvironments = "production"
	CreateScheduleRequestEnvironmentsStaging     CreateScheduleRequestEnvironments = "staging"
)

// Valid indicates whether the value is a known member of the CreateScheduleRequestEnvironments enum.
func (e CreateScheduleRequestEnvironments) Valid() bool {
	switch e {
	case CreateScheduleRequestEnvironmentsDevelopment:
		return true
	case CreateScheduleRequestEnvironmentsProduction:
		return true
	case CreateScheduleRequestEnvironmentsStaging:
		return true
	default:
		return false
	}
}

// Defines values for ScheduleEnvironments.
const (
	ScheduleEnvironmentsDevelopment ScheduleEnvironments = "development"
	ScheduleEnvironmentsProduction  ScheduleEnvironments = "production"
	ScheduleEnvironmentsStaging     ScheduleEnvironments = "staging"
)

// Valid indicates whether the value is a known member of the ScheduleEnvironments enum.
func (e ScheduleEnvironments) Valid() bool {
	switch e {
	case ScheduleEnvironmentsDevelopment:
		return true
	case ScheduleEnvironmentsProduction:
		return true
	case ScheduleEnvironmentsStaging:
		return true
	default:
		return false
	}
}

// Defines values for ScheduleStatus.
const (
	ScheduleStatusApproved ScheduleStatus = "approved"
	ScheduleStatusCreated  ScheduleStatus = "created"
	ScheduleStatusDenied   ScheduleStatus = "denied"
)

// Valid indicates whether the value is a known member of the ScheduleStatus enum.
func (e ScheduleStatus) Valid() bool {
	switch e {
	case ScheduleStatusApproved:
		return true
	case ScheduleStatusCreated:
		return true
	case ScheduleStatusDenied:
		return true
	default:
		return false
	}
}

// Defines values for UpdateScheduleRequestEnvironments.
const (
	UpdateScheduleRequestEnvironmentsDevelopment UpdateScheduleRequestEnvironments = "development"
	UpdateScheduleRequestEnvironmentsProduction  UpdateScheduleRequestEnvironments = "production"
	UpdateScheduleRequestEnvironmentsStaging     UpdateScheduleRequestEnvironments = "staging"
)

// Valid indicates whether the value is a known member of the UpdateScheduleRequestEnvironments enum.
func (e UpdateScheduleRequestEnvironments) Valid() bool {
	switch e {
	case UpdateScheduleRequestEnvironmentsDevelopment:
		return true
	case UpdateScheduleRequestEnvironmentsProduction:
		return true
	case UpdateScheduleRequestEnvironmentsStaging:
		return true
	default:
		return false
	}
}

// Defines values for UserRole.
const (
	UserRoleAdmin    UserRole = "admin"
	UserRoleDeployer UserRole = "deployer"
	UserRoleViewer   UserRole = "viewer"
)

// Valid indicates whether the value is a known member of the UserRole enum.
func (e UserRole) Valid() bool {
	switch e {
	case UserRoleAdmin:
		return true
	case UserRoleDeployer:
		return true
	case UserRoleViewer:
		return true
	default:
		return false
	}
}

// Defines values for ListSchedulesParamsEnvironment.
const (
	ListSchedulesParamsEnvironmentDevelopment ListSchedulesParamsEnvironment = "development"
	ListSchedulesParamsEnvironmentProduction  ListSchedulesParamsEnvironment = "production"
	ListSchedulesParamsEnvironmentStaging     ListSchedulesParamsEnvironment = "staging"
)

// Valid indicates whether the value is a known member of the ListSchedulesParamsEnvironment enum.
func (e ListSchedulesParamsEnvironment) Valid() bool {
	switch e {
	case ListSchedulesParamsEnvironmentDevelopment:
		return true
	case ListSchedulesParamsEnvironmentProduction:
		return true
	case ListSchedulesParamsEnvironmentStaging:
		return true
	default:
		return false
	}
}

// Defines values for ListSchedulesParamsStatus.
const (
	ListSchedulesParamsStatusApproved ListSchedulesParamsStatus = "approved"
	ListSchedulesParamsStatusCreated  ListSchedulesParamsStatus = "created"
	ListSchedulesParamsStatusDenied   ListSchedulesParamsStatus = "denied"
)

// Valid indicates whether the value is a known member of the ListSchedulesParamsStatus enum.
func (e ListSchedulesParamsStatus) Valid() bool {
	switch e {
	case ListSchedulesParamsStatusApproved:
		return true
	case ListSchedulesParamsStatusCreated:
		return true
	case ListSchedulesParamsStatusDenied:
		return true
	default:
		return false
	}
}

// Defines values for ListUsersParamsRole.
const (
	ListUsersParamsRoleAdmin    ListUsersParamsRole = "admin"
	ListUsersParamsRoleDeployer ListUsersParamsRole = "deployer"
	ListUsersParamsRoleViewer   ListUsersParamsRole = "viewer"
)

// Valid indicates whether the value is a known member of the ListUsersParamsRole enum.
func (e ListUsersParamsRole) Valid() bool {
	switch e {
	case ListUsersParamsRoleAdmin:
		return true
	case ListUsersParamsRoleDeployer:
		return true
	case ListUsersParamsRoleViewer:
		return true
	default:
		return false
	}
}

// Defines values for AssignRoleJSONBodyRole.
const (
	Admin    AssignRoleJSONBodyRole = "admin"
	Deployer AssignRoleJSONBodyRole = "deployer"
	Viewer   AssignRoleJSONBodyRole = "viewer"
)

// Valid indicates whether the value is a known member of the AssignRoleJSONBodyRole enum.
func (e AssignRoleJSONBodyRole) Valid() bool {
	switch e {
	case Admin:
		return true
	case Deployer:
		return true
	case Viewer:
		return true
	default:
		return false
	}
}

// AssignScheduleRequest defines model for AssignScheduleRequest.
type AssignScheduleRequest struct {
	// AssignedBy User who performed the assignment
	AssignedBy *string `json:"assignedBy,omitempty"`

	// GroupIds Array of group IDs to assign the schedule to
	GroupIds []openapi_types.UUID `json:"groupIds"`
}

// BulkAssignRequest defines model for BulkAssignRequest.
type BulkAssignRequest struct {
	// AssignedBy User who performed the assignment
	AssignedBy *string `json:"assignedBy,omitempty"`

	// ScheduleIds Array of schedule IDs to assign to the group
	ScheduleIds []openapi_types.UUID `json:"scheduleIds"`
}

// CreateGroupRequest defines model for CreateGroupRequest.
type CreateGroupRequest struct {
	// Description Optional description of the group
	Description *string `json:"description,omitempty"`

	// Name Name of the group
	Name string `json:"name"`

	// Owner Owner of the group
	Owner string `json:"owner"`
}

// CreateScheduleRequest defines model for CreateScheduleRequest.
type CreateScheduleRequest struct {
	// Description Optional description of the deployment
	Description *string `json:"description,omitempty"`

	// Environments Target environments
	Environments []CreateScheduleRequestEnvironments `json:"environments"`

	// Owners Owners of the schedule
	Owners []string `json:"owners"`

	// RollbackPlan Optional rollback plan for the deployment
	RollbackPlan *string `json:"rollbackPlan,omitempty"`

	// ScheduledAt When the deployment is scheduled (ISO 8601)
	ScheduledAt time.Time `json:"scheduledAt"`

	// ServiceName Name of the service to deploy
	ServiceName string `json:"serviceName"`
}

// CreateScheduleRequestEnvironments defines model for CreateScheduleRequest.Environments.
type CreateScheduleRequestEnvironments string

// Error defines model for Error.
type Error struct {
	// Details Additional error details
	Details *string `json:"details,omitempty"`

	// Message Error message
	Message string `json:"message"`
}

// Group defines model for Group.
type Group struct {
	// CreatedAt When the group was created
	CreatedAt time.Time `json:"createdAt"`

	// Description Optional description of the group
	Description *string `json:"description,omitempty"`

	// Id Unique group identifier
	Id openapi_types.UUID `json:"id"`

	// IsFavorite Whether this group is favorited by the authenticated user
	IsFavorite *bool `json:"isFavorite,omitempty"`

	// Name Name of the group
	Name string `json:"name"`

	// Owner Owner of the group (immutable after creation)
	Owner string `json:"owner"`

	// UpdatedAt When the group was last updated
	UpdatedAt time.Time `json:"updatedAt"`
}

// Schedule defines model for Schedule.
type Schedule struct {
	// CreatedAt When the schedule was created
	CreatedAt time.Time `json:"createdAt"`
	CreatedBy User      `json:"createdBy"`

	// Description Optional description of the deployment
	Description *string `json:"description,omitempty"`

	// Environments Target environments
	Environments []ScheduleEnvironments `json:"environments"`

	// Groups Groups this schedule belongs to
	Groups *[]Group `json:"groups,omitempty"`

	// Id Unique schedule identifier
	Id openapi_types.UUID `json:"id"`

	// Owners Owners of the schedule
	Owners []string `json:"owners"`

	// RollbackPlan Optional rollback plan for the deployment
	RollbackPlan *string `json:"rollbackPlan,omitempty"`

	// ScheduledAt When the deployment is scheduled (ISO 8601)
	ScheduledAt time.Time `json:"scheduledAt"`

	// ServiceName Name of the service to deploy
	ServiceName string `json:"serviceName"`

	// Status Approval status of the schedule
	Status ScheduleStatus `json:"status"`

	// UpdatedAt When the schedule was last updated
	UpdatedAt time.Time `json:"updatedAt"`
	UpdatedBy *User     `json:"updatedBy,omitempty"`
}

// ScheduleEnvironments defines model for Schedule.Environments.
type ScheduleEnvironments string

// ScheduleStatus Approval status of the schedule
type ScheduleStatus string

// UpdateGroupRequest defines model for UpdateGroupRequest.
type UpdateGroupRequest struct {
	// Description Optional description of the group
	Description *string `json:"description,omitempty"`

	// Name Name of the group
	Name string `json:"name"`
}

// UpdateScheduleRequest defines model for UpdateScheduleRequest.
type UpdateScheduleRequest struct {
	// Description Optional description of the deployment
	Description *string `json:"description,omitempty"`

	// Environments Target environments (replaces entire list)
	Environments *[]UpdateScheduleRequestEnvironments `json:"environments,omitempty"`

	// Owners Owners of the schedule (replaces entire list)
	Owners *[]string `json:"owners,omitempty"`

	// RollbackPlan Optional rollback plan for the deployment
	RollbackPlan *string `json:"rollbackPlan,omitempty"`

	// ScheduledAt When the deployment is scheduled (ISO 8601)
	ScheduledAt *time.Time `json:"scheduledAt,omitempty"`

	// ServiceName Name of the service to deploy
	ServiceName *string `json:"serviceName,omitempty"`
}

// UpdateScheduleRequestEnvironments defines model for UpdateScheduleRequest.Environments.
type UpdateScheduleRequestEnvironments string

// User defines model for User.
type User struct {
	// CreatedAt When the user was created
	CreatedAt time.Time `json:"createdAt"`

	// Email User email address
	Email openapi_types.Email `json:"email"`

	// Id Unique user identifier
	Id openapi_types.UUID `json:"id"`

	// LastLoginAt When the user last logged in
	LastLoginAt *time.Time `json:"lastLoginAt,omitempty"`

	// Name User display name
	Name string `json:"name"`

	// Role User role
	Role UserRole `json:"role"`

	// UpdatedAt When the user was last updated
	UpdatedAt time.Time `json:"updatedAt"`
}

// UserRole User role
type UserRole string

// GoogleCallbackParams defines parameters for GoogleCallback.
type GoogleCallbackParams struct {
	// Code Authorization code from Google
	Code string `form:"code" json:"code"`

	// State State parameter for CSRF protection
	State string `form:"state" json:"state"`
}

// ListGroupsParams defines parameters for ListGroups.
type ListGroupsParams struct {
	// Owner Filter groups by owner
	Owner string `form:"owner" json:"owner"`
}

// ListSchedulesParams defines parameters for ListSchedules.
type ListSchedulesParams struct {
	// From Start date for filtering (ISO 8601 format)
	From *time.Time `form:"from,omitempty" json:"from,omitempty"`

	// To End date for filtering (ISO 8601 format)
	To *time.Time `form:"to,omitempty" json:"to,omitempty"`

	// Environment Filter by environment (can specify multiple)
	Environment *[]ListSchedulesParamsEnvironment `form:"environment,omitempty" json:"environment,omitempty"`

	// Owner Filter by owner (can specify multiple)
	Owner *[]string `form:"owner,omitempty" json:"owner,omitempty"`

	// Status Filter by status
	Status *ListSchedulesParamsStatus `form:"status,omitempty" json:"status,omitempty"`

	// Ungrouped Filter for schedules not assigned to any group
	Ungrouped *bool `form:"ungrouped,omitempty" json:"ungrouped,omitempty"`
}

// ListSchedulesParamsEnvironment defines parameters for ListSchedules.
type ListSchedulesParamsEnvironment string

// ListSchedulesParamsStatus defines parameters for ListSchedules.
type ListSchedulesParamsStatus string

// ListUsersParams defines parameters for ListUsers.
type ListUsersParams struct {
	// Role Filter by role
	Role *ListUsersParamsRole `form:"role,omitempty" json:"role,omitempty"`
}

// ListUsersParamsRole defines parameters for ListUsers.
type ListUsersParamsRole string

// AssignRoleJSONBody defines parameters for AssignRole.
type AssignRoleJSONBody struct {
	// Role New role to assign
	Role AssignRoleJSONBodyRole `json:"role"`
}

// AssignRoleJSONBodyRole defines parameters for AssignRole.
type AssignRoleJSONBodyRole string

// CreateGroupJSONRequestBody defines body for CreateGroup for application/json ContentType.
type CreateGroupJSONRequestBody = CreateGroupRequest

// UpdateGroupJSONRequestBody defines body for UpdateGroup for application/json ContentType.
type UpdateGroupJSONRequestBody = UpdateGroupRequest

// BulkAssignSchedulesJSONRequestBody defines body for BulkAssignSchedules for application/json ContentType.
type BulkAssignSchedulesJSONRequestBody = BulkAssignRequest

// CreateScheduleJSONRequestBody defines body for CreateSchedule for application/json ContentType.
type CreateScheduleJSONRequestBody = CreateScheduleRequest

// UpdateScheduleJSONRequestBody defines body for UpdateSchedule for application/json ContentType.
type UpdateScheduleJSONRequestBody = UpdateScheduleRequest

// AssignScheduleToGroupsJSONRequestBody defines body for AssignScheduleToGroups for application/json ContentType.
type AssignScheduleToGroupsJSONRequestBody = AssignScheduleRequest

// AssignRoleJSONRequestBody defines body for AssignRole for application/json ContentType.
type AssignRoleJSONRequestBody AssignRoleJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Google OAuth callback
	// (GET /auth/google/callback)
	GoogleCallback(w http.ResponseWriter, r *http.Request, params GoogleCallbackParams)
	// Initiate Google OAuth login
	// (GET /auth/google/login)
	GoogleLogin(w http.ResponseWriter, r *http.Request)
	// Logout and revoke token
	// (POST /auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)
	// Refresh JWT token
	// (POST /auth/refresh)
	RefreshToken(w http.ResponseWriter, r *http.Request)
	// List groups for an owner
	// (GET /groups)
	ListGroups(w http.ResponseWriter, r *http.Request, params ListGroupsParams)
	// Create a new group
	// (POST /groups)
	CreateGroup(w http.ResponseWriter, r *http.Request)
	// Delete a group
	// (DELETE /groups/{id})
	DeleteGroup(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Get a group by ID
	// (GET /groups/{id})
	GetGroup(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Update a group
	// (PUT /groups/{id})
	UpdateGroup(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Remove favorite status from a group
	// (DELETE /groups/{id}/favorite)
	UnfavoriteGroup(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Mark a group as favorite
	// (POST /groups/{id}/favorite)
	FavoriteGroup(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Get schedules in a group
	// (GET /groups/{id}/schedules)
	GetSchedulesInGroup(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Bulk assign schedules to group
	// (POST /groups/{id}/schedules)
	BulkAssignSchedules(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// List deployment schedules
	// (GET /schedules)
	ListSchedules(w http.ResponseWriter, r *http.Request, params ListSchedulesParams)
	// Create a new deployment schedule
	// (POST /schedules)
	CreateSchedule(w http.ResponseWriter, r *http.Request)
	// Delete a schedule
	// (DELETE /schedules/{id})
	DeleteSchedule(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Get a schedule by ID
	// (GET /schedules/{id})
	GetSchedule(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Update a schedule
	// (PUT /schedules/{id})
	UpdateSchedule(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Approve a schedule
	// (POST /schedules/{id}/approve)
	ApproveSchedule(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Deny a schedule
	// (POST /schedules/{id}/deny)
	DenySchedule(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Get groups for a schedule
	// (GET /schedules/{id}/groups)
	GetGroupsForSchedule(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Assign schedule to groups
	// (POST /schedules/{id}/groups)
	AssignScheduleToGroups(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Unassign schedule from group
	// (DELETE /schedules/{id}/groups/{groupId})
	UnassignScheduleFromGroup(w http.ResponseWriter, r *http.Request, id openapi_types.UUID, groupId openapi_types.UUID)
	// List all users (admin only)
	// (GET /users)
	ListUsers(w http.ResponseWriter, r *http.Request, params ListUsersParams)
	// Get current user profile
	// (GET /users/me)
	GetMyProfile(w http.ResponseWriter, r *http.Request)
	// Get user by ID (admin only)
	// (GET /users/{id})
	GetUserByID(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Assign role to user (admin only)
	// (PUT /users/{id}/role)
	AssignRole(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Google OAuth callback
// (GET /auth/google/callback)
func (_ Unimplemented) GoogleCallback(w http.ResponseWriter, r *http.Request, params GoogleCallbackParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Initiate Google OAuth login
// (GET /auth/google/login)
func (_ Unimplemented) GoogleLogin(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Logout and revoke token
// (POST /auth/logout)
func (_ Unimplemented) Logout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Refresh JWT token
// (POST /auth/refresh)
func (_ Unimplemented) RefreshToken(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List groups for an owner
// (GET /groups)
func (_ Unimplemented) ListGroups(w http.ResponseWriter, r *http.Request, params ListGroupsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new group
// (POST /groups)
func (_ Unimplemented) CreateGroup(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a group
// (DELETE /groups/{id})
func (_ Unimplemented) DeleteGroup(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a group by ID
// (GET /groups/{id})
func (_ Unimplemented) GetGroup(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a group
// (PUT /groups/{id})
func (_ Unimplemented) UpdateGroup(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Remove favorite status from a group
// (DELETE /groups/{id}/favorite)
func (_ Unimplemented) UnfavoriteGroup(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Mark a group as favorite
// (POST /groups/{id}/favorite)
func (_ Unimplemented) FavoriteGroup(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get schedules in a group
// (GET /groups/{id}/schedules)
func (_ Unimplemented) GetSchedulesInGroup(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Bulk assign schedules to group
// (POST /groups/{id}/schedules)
func (_ Unimplemented) BulkAssignSchedules(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List deployment schedules
// (GET /schedules)
func (_ Unimplemented) ListSchedules(w http.ResponseWriter, r *http.Request, params ListSchedulesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new deployment schedule
// (POST /schedules)
func (_ Unimplemented) CreateSchedule(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a schedule
// (DELETE /schedules/{id})
func (_ Unimplemented) DeleteSchedule(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a schedule by ID
// (GET /schedules/{id})
func (_ Unimplemented) GetSchedule(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a schedule
// (PUT /schedules/{id})
func (_ Unimplemented) UpdateSchedule(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Approve a schedule
// (POST /schedules/{id}/approve)
func (_ Unimplemented) ApproveSchedule(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Deny a schedule
// (POST /schedules/{id}/deny)
func (_ Unimplemented) DenySchedule(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get groups for a schedule
// (GET /schedules/{id}/groups)
func (_ Unimplemented) GetGroupsForSchedule(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Assign schedule to groups
// (POST /schedules/{id}/groups)
func (_ Unimplemented) AssignScheduleToGroups(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Unassign schedule from group
// (DELETE /schedules/{id}/groups/{groupId})
func (_ Unimplemented) UnassignScheduleFromGroup(w http.ResponseWriter, r *http.Request, id openapi_types.UUID, groupId openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List all users (admin only)
// (GET /users)
func (_ Unimplemented) ListUsers(w http.ResponseWriter, r *http.Request, params ListUsersParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get current user profile
// (GET /users/me)
func (_ Unimplemented) GetMyProfile(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get user by ID (admin only)
// (GET /users/{id})
func (_ Unimplemented) GetUserByID(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Assign role to user (admin only)
// (PUT /users/{id}/role)
func (_ Unimplemented) AssignRole(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GoogleCallback operation middleware
func (siw *ServerInterfaceWrapper) GoogleCallback(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GoogleCallbackParams

	// ------------- Required query parameter "code" -------------

	if paramValue := r.URL.Query().Get("code"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "code"})
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "code", r.URL.Query(), &params.Code, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "code", Err: err})
		return
	}

	// ------------- Required query parameter "state" -------------

	if paramValue := r.URL.Query().Get("state"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "state"})
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "state", r.URL.Query(), &params.State, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "state", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GoogleCallback(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GoogleLogin operation middleware
func (siw *ServerInterfaceWrapper) GoogleLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GoogleLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RefreshToken operation middleware
func (siw *ServerInterfaceWrapper) RefreshToken(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RefreshToken(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListGroups operation middleware
func (siw *ServerInterfaceWrapper) ListGroups(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListGroupsParams

	// ------------- Required query parameter "owner" -------------

	if paramValue := r.URL.Query().Get("owner"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "owner"})
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "owner", r.URL.Query(), &params.Owner, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "owner", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListGroups(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateGroup operation middleware
func (siw *ServerInterfaceWrapper) CreateGroup(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateGroup(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteGroup operation middleware
func (siw *ServerInterfaceWrapper) DeleteGroup(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteGroup(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetGroup operation middleware
func (siw *ServerInterfaceWrapper) GetGroup(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetGroup(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateGroup operation middleware
func (siw *ServerInterfaceWrapper) UpdateGroup(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateGroup(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UnfavoriteGroup operation middleware
func (siw *ServerInterfaceWrapper) UnfavoriteGroup(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UnfavoriteGroup(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// FavoriteGroup operation middleware
func (siw *ServerInterfaceWrapper) FavoriteGroup(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.FavoriteGroup(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSchedulesInGroup operation middleware
func (siw *ServerInterfaceWrapper) GetSchedulesInGroup(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSchedulesInGroup(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// BulkAssignSchedules operation middleware
func (siw *ServerInterfaceWrapper) BulkAssignSchedules(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.BulkAssignSchedules(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListSchedules operation middleware
func (siw *ServerInterfaceWrapper) ListSchedules(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListSchedulesParams

	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "from", r.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		return
	}

	// ------------- Optional query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "to", r.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		return
	}

	// ------------- Optional query parameter "environment" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "environment", r.URL.Query(), &params.Environment, runtime.BindQueryParameterOptions{Type: "array", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "environment", Err: err})
		return
	}

	// ------------- Optional query parameter "owner" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "owner", r.URL.Query(), &params.Owner, runtime.BindQueryParameterOptions{Type: "array", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "owner", Err: err})
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		return
	}

	// ------------- Optional query parameter "ungrouped" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "ungrouped", r.URL.Query(), &params.Ungrouped, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "ungrouped", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSchedules(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateSchedule operation middleware
func (siw *ServerInterfaceWrapper) CreateSchedule(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateSchedule(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteSchedule operation middleware
func (siw *ServerInterfaceWrapper) DeleteSchedule(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteSchedule(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSchedule operation middleware
func (siw *ServerInterfaceWrapper) GetSchedule(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSchedule(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateSchedule operation middleware
func (siw *ServerInterfaceWrapper) UpdateSchedule(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateSchedule(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ApproveSchedule operation middleware
func (siw *ServerInterfaceWrapper) ApproveSchedule(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ApproveSchedule(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DenySchedule operation middleware
func (siw *ServerInterfaceWrapper) DenySchedule(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DenySchedule(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetGroupsForSchedule operation middleware
func (siw *ServerInterfaceWrapper) GetGroupsForSchedule(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetGroupsForSchedule(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AssignScheduleToGroups operation middleware
func (siw *ServerInterfaceWrapper) AssignScheduleToGroups(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AssignScheduleToGroups(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UnassignScheduleFromGroup operation middleware
func (siw *ServerInterfaceWrapper) UnassignScheduleFromGroup(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// ------------- Path parameter "groupId" -------------
	var groupId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "groupId", chi.URLParam(r, "groupId"), &groupId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "groupId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UnassignScheduleFromGroup(w, r, id, groupId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListUsers operation middleware
func (siw *ServerInterfaceWrapper) ListUsers(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListUsersParams

	// ------------- Optional query parameter "role" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "role", r.URL.Query(), &params.Role, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "role", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListUsers(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMyProfile operation middleware
func (siw *ServerInterfaceWrapper) GetMyProfile(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMyProfile(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUserByID operation middleware
func (siw *ServerInterfaceWrapper) GetUserByID(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserByID(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AssignRole operation middleware
func (siw *ServerInterfaceWrapper) AssignRole(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AssignRole(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/google/callback", wrapper.GoogleCallback)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/google/login", wrapper.GoogleLogin)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/logout", wrapper.Logout)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/refresh", wrapper.RefreshToken)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/groups", wrapper.ListGroups)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/groups", wrapper.CreateGroup)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/groups/{id}", wrapper.DeleteGroup)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/groups/{id}", wrapper.GetGroup)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/groups/{id}", wrapper.UpdateGroup)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/groups/{id}/favorite", wrapper.UnfavoriteGroup)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/groups/{id}/favorite", wrapper.FavoriteGroup)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/groups/{id}/schedules", wrapper.GetSchedulesInGroup)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/groups/{id}/schedules", wrapper.BulkAssignSchedules)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/schedules", wrapper.ListSchedules)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/schedules", wrapper.CreateSchedule)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/schedules/{id}", wrapper.DeleteSchedule)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/schedules/{id}", wrapper.GetSchedule)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/schedules/{id}", wrapper.UpdateSchedule)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/schedules/{id}/approve", wrapper.ApproveSchedule)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/schedules/{id}/deny", wrapper.DenySchedule)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/schedules/{id}/groups", wrapper.GetGroupsForSchedule)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/schedules/{id}/groups", wrapper.AssignScheduleToGroups)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/schedules/{id}/groups/{groupId}", wrapper.UnassignScheduleFromGroup)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/users", wrapper.ListUsers)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/users/me", wrapper.GetMyProfile)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/users/{id}", wrapper.GetUserByID)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/users/{id}/role", wrapper.AssignRole)
	})

	return r
}
